### PR TITLE
AWSM daily running 1 more hour than needed

### LINKED ISSUE #55: AWSM daily running 1 more hour than needed
In `awsm_daily_airflow` the end date is 24 hours from the start date meaning that the next day's folder will be created with one value in it (for the `00:00` time). Changing it to 23 hours would make it stop after completing the `23:00` run and not make a new day.

This does not have any affect on how the model runs as the value will be recalculated for the next day, making the `00:00` hour calculated twice.

### PR DESCRIPTION
**Pull request by scotthavens**
updated from 24 hours to 23 hours fix #55

### CODE REVIEW

**Comment by jomey** [comment]
Can we merge this?

I am currently going through the SMRF outputs and it requires an additional filter for each day to exclude the extra time step at 00:00 for the next day.

**Comment by scotthavens** [comment]
Forgot about this one!

**Comment by jomey** [comment]
Thank you!

**Comment by scotthavens** [comment]
FYI, this should be fixed already in the `main` branch.

**Comment by jomey** [comment]
> FYI, this should be fixed already in the `main` branch.

Hm ... [Does not look like it](https://github.com/USDA-ARS-NWRC/awsm/blob/37a64df43b260a0dd0fb7be683feac19cf038de6/scripts/awsm_daily_airflow#L22)

New PR?

**Comment by scotthavens** [comment]
Hmm, guess "fixed" was a relative term.

I don't think that the daily is setup to run how it once was, I'd have to check as I was making a lot of changes to the way AWSM was ran. Off the top of my head, you should be able to run it in a daily mode but write to the same netcdf output files, bypassing the daily folders. It should also have written out to daily folders but the script may not have been fixed.

**Comment by jomey** [comment]
Trying to follow your train of thought.

I have daily outputs, but basically each day also has a '00:00' hour for the next day. This I attributed to this fix, where SMRF was given 25 hours. Is that correct?

Will there be a different behavior on main, no longer producing daily output files?

**Comment by scotthavens** [comment]
Haven't been in AWSM/SMRF world for a while... But yes, this was merged to `release-0.10` which will remove the 00:00 hour from the daily SMRF files.

In `main`, I started with making sure the AWSM would run in the standard start/end date folder structure and the output files would be appended. This is intended to replace the daily folder and make it easier to work with the files, especially when using HRRR. However, I don't think I've finished the daily AWSM folder creation that would make it like how you and `release-0.10` are running.

**Pull request merged**
