### PR TITLE
Remove HRRR forecast flag

### PR DESCRIPTION
**Pull request by jomey**
Follow up request for removing the HRRR forecast flag in USDA-ARS-NWRC/smrf/pull/205

Also removed a method call in `run_awsm`, which definition was commented out.

### CODE REVIEW

**Comment by scotthavens** [comment]
Look like an old `weather_forecast_retrieval.hrrr` import which was removed.

**Comment by jomey** [comment]
> Look like an old `weather_forecast_retrieval.hrrr` import which was removed.

SMRF needs a new release to include the updates to the import of WFR v0.7.1, which is installed via pip.
You good with cutting a new 0.11.8?

**Comment by scotthavens** [comment]
Sure, v0.11.7 will work, all the others were pre releases for testing the deployment.

**Comment by jomey** [comment]
SMRF release adressed the import error.
However, the OS X job has an interesting one: https://travis-ci.com/github/USDA-ARS-NWRC/awsm/jobs/506653187
Have you seen that before?
```
ImportError: Failed to import test module: awsm
```

Lower down there is also this message:
```
ImportError: dlopen(/Users/travis/build/USDA-ARS-NWRC/awsm/.tox/py37/lib/python3.7/site-packages/smrf/utils/wind/wind_c.cpython-37m-darwin.so, 2): Symbol not found: _aligned_alloc
```

**Comment by jomey** [comment]
The other builds are failing with this:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
I noticed this myself locally, where tests with iPySnobal seem to be hung or stuck. This is with the current master too and I first accepted this as a possible issue on my machine.
Are you able to run them locally?

**Comment by scotthavens** [comment]
Ugh. Never seen that before. It's complaining that the SMRF wind was compiled for 10.15, try ` xcode11.4` in Travis to see if that helps?

It appears to be some compilation issue with the C code for either the wind or pysnobal.

**Comment by jomey** [comment]
> Ugh. Never seen that before. It's complaining that the SMRF wind was compiled for 10.15, try ` xcode11.4` in Travis to see if that helps?
> 
> It appears to be some compilation issue with the C code for either the wind or pysnobal.

Bumping XCode addressed this issue. Now there is only the mystery of the hanging iPySnobal

**Comment by jomey** [comment]
My next guess is that the tests are not ready for the TopoCalc updates. Might need an update for the Gold files first

**Comment by scotthavens** [comment]
Does this pass locally for you?

**Comment by jomey** [comment]
I see the same issues as Travis, where tests using iPySnobal don't finish. Then also the differences to gold files, which I attribute to TopoCalc changes. Getting same errors when running master on my local without these changes.

Should there be a PR first, updating the Gold files with latest of TopoCalc v0.5 ?

**Comment by scotthavens** [comment]
Yeah, let's do a PR for topocalc v0.5.

You could also try the version <0.5 as a test to see if it's attributed to topocalc.

**Comment by jomey** [comment]
> Yeah, let's do a PR for topocalc v0.5.
> 

Do you want to create the files on a 'true' gold host and push a branch?
I will then do the comparison with goldmeister and open the PR

**Comment by scotthavens** [comment]
Updated the gold but there is another issue with the threading in Lakes with HRRR. Looking into it now.

**Comment by jomey** [comment]
> Updated the gold but there is another issue with the threading in Lakes with HRRR. Looking into it now.

It hangs for me at the step of `Distributing thermal` in SMRF. That is the last log entry I get

**Comment by scotthavens** [comment]
Me too but I've found with the threading, that isn't always where it crashes. Usually it's a dependent of thermal

**Review by scotthavens — APPROVED** [review]

**Pull request merged**
